site_name: apt2bom
site_url: https://github.com/thir820/apt2bom
nav:
  - Home: index.md
  - Example: example.md
repo_url: https://github.com/thir820/apt2bom
edit_uri: edit/main/docs_src/
theme: readthedocs
docs_dir: docs_src
site_dir: docs